from __future__ import annotations

import json
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "apps" / "web"


class WebScaffoldTests(unittest.TestCase):
    def test_package_manifest_has_core_scripts(self) -> None:
        package_json = json.loads((WEB_ROOT / "package.json").read_text(encoding="utf-8"))
        self.assertEqual(package_json["name"], "trust-ledger-web")
        self.assertIn("dev", package_json["scripts"])
        self.assertIn("build", package_json["scripts"])
        self.assertIn("test", package_json["scripts"])
        self.assertIn("preview", package_json["scripts"])
        self.assertIn("react", package_json["dependencies"])
        self.assertIn("react-router-dom", package_json["dependencies"])

    def test_pwa_files_and_metadata_exist(self) -> None:
        index_html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        manifest = (WEB_ROOT / "public" / "manifest.webmanifest").read_text(encoding="utf-8")
        service_worker = (WEB_ROOT / "public" / "sw.js").read_text(encoding="utf-8")
        icon = (WEB_ROOT / "public" / "icon.svg").read_text(encoding="utf-8")
        self.assertIn('rel="manifest"', index_html)
        self.assertIn('name="theme-color"', index_html)
        self.assertIn('"display": "standalone"', manifest)
        self.assertIn('addEventListener("fetch"', service_worker)
        self.assertIn("<svg", icon)

    def test_web_env_examples_cover_api_base_and_dev_proxy_target(self) -> None:
        env_example = (WEB_ROOT / ".env.example").read_text(encoding="utf-8")
        self.assertIn("VITE_TRUST_LEDGER_API_BASE_URL=", env_example)
        self.assertIn("VITE_TRUST_LEDGER_DEV_API_PROXY_TARGET=", env_example)

    def test_router_scaffold_includes_public_and_protected_paths(self) -> None:
        router_source = (WEB_ROOT / "src" / "app" / "router.js").read_text(encoding="utf-8")
        self.assertIn('path: "/"', router_source)
        self.assertIn('path: "login"', router_source)
        self.assertIn('path: "register"', router_source)
        self.assertIn('path: "/app"', router_source)
        self.assertIn('path: "trust"', router_source)
        self.assertIn('path: "marketplace"', router_source)
        self.assertIn('path: "records"', router_source)
        self.assertIn('path: "operations"', router_source)
        self.assertIn('path: "security"', router_source)
        self.assertIn('path: "internal"', router_source)
        self.assertIn("RequireAuth", router_source)
        self.assertIn("RequirePersonalWorkspace", router_source)
        self.assertIn("RequireInternalAccess", router_source)

    def test_session_layer_wires_real_auth_endpoints(self) -> None:
        session_source = (WEB_ROOT / "src" / "app" / "session.js").read_text(encoding="utf-8")
        api_source = (WEB_ROOT / "src" / "lib" / "api.js").read_text(encoding="utf-8")
        i18n_source = (WEB_ROOT / "src" / "lib" / "i18n.js").read_text(encoding="utf-8")
        main_source = (WEB_ROOT / "src" / "main.js").read_text(encoding="utf-8")
        vite_source = (WEB_ROOT / "vite.config.js").read_text(encoding="utf-8")
        shell_source = (WEB_ROOT / "src" / "app" / "AppShell.js").read_text(encoding="utf-8")
        self.assertIn('/auth/me', session_source)
        self.assertIn('/auth/login', session_source)
        self.assertIn('/auth/register', session_source)
        self.assertIn('/auth/logout', session_source)
        self.assertIn("workspace_roles", session_source)
        self.assertIn("getAvailableWorkspaceRoles", session_source)
        self.assertIn("VITE_TRUST_LEDGER_API_BASE_URL", api_source)
        self.assertIn("formatApiErrorMessage", api_source)
        self.assertIn('detail.loc.join(" > ")', api_source)
        self.assertIn("translateText", api_source)
        self.assertIn("LanguageProvider", i18n_source)
        self.assertIn("language-dock", i18n_source)
        self.assertIn('SUPPORTED_LANGUAGES = ["en", "el"]', i18n_source)
        self.assertIn("beforeinstallprompt", main_source)
        self.assertIn("serviceWorker.register", main_source)
        self.assertIn("LanguageProvider", main_source)
        self.assertIn("useLanguage", main_source)
        self.assertIn("ApplicationRoot", main_source)
        self.assertIn('key: "router-" + language', main_source)
        self.assertIn("VITE_TRUST_LEDGER_DEV_API_PROXY_TARGET", vite_source)
        self.assertIn('label: "Home"', shell_source)
        self.assertIn('"Landlord Trust"', shell_source)
        self.assertIn('"Tenant Trust"', shell_source)
        self.assertIn('label: "Rental Records"', shell_source)
        self.assertIn('label: "Rent & Issues"', shell_source)
        self.assertIn('label: "Agency Tools"', shell_source)
        self.assertIn('"Admin Center"', shell_source)
        self.assertIn('"Review Center"', shell_source)

    def test_feature_pages_are_wired_to_live_rebuild_endpoints(self) -> None:
        workspace_source = (WEB_ROOT / "src" / "pages" / "WorkspaceHomePage.js").read_text(encoding="utf-8")
        agency_source = (WEB_ROOT / "src" / "pages" / "AgencyWorkbenchPage.js").read_text(encoding="utf-8")
        internal_source = (WEB_ROOT / "src" / "pages" / "InternalOperationsPage.js").read_text(encoding="utf-8")
        auth_source = (WEB_ROOT / "src" / "pages" / "AuthPage.js").read_text(encoding="utf-8")
        marketplace_source = (WEB_ROOT / "src" / "pages" / "MarketplacePage.js").read_text(encoding="utf-8")
        records_source = (WEB_ROOT / "src" / "pages" / "RecordsPage.js").read_text(encoding="utf-8")
        operations_source = (WEB_ROOT / "src" / "pages" / "OperationsPage.js").read_text(encoding="utf-8")
        trust_source = (WEB_ROOT / "src" / "pages" / "TrustProfilePage.js").read_text(encoding="utf-8")
        score_transparency_source = (WEB_ROOT / "src" / "lib" / "scoreTransparency.js").read_text(
            encoding="utf-8"
        )
        score_component_source = (
            WEB_ROOT / "src" / "components" / "ScoreTransparency.js"
        ).read_text(encoding="utf-8")

        self.assertIn('/organizations/mine', workspace_source)
        self.assertIn('/trust-scores/mine', workspace_source)
        self.assertIn("Installable workspace", workspace_source)
        self.assertIn('/organizations/mine', agency_source)
        self.assertIn('/organizations/" + organizationId + "/commercial-overview', agency_source)
        self.assertIn('/organizations/" + organizationId + "/listings', agency_source)
        self.assertIn('/organizations/" + organizationId + "/applications', agency_source)
        self.assertIn('/organizations/" + organizationId + "/trust-checks', agency_source)
        self.assertIn('/organizations/" + organizationId + "/memberships', agency_source)
        self.assertIn('path += "/validate"', agency_source)
        self.assertIn('path += "/profile"', agency_source)
        self.assertIn('/screening-dashboard', agency_source)
        self.assertIn('/properties/mine', agency_source)
        self.assertIn('/properties', agency_source)
        self.assertIn('/properties/" + propertyRecord.id', agency_source)
        self.assertIn('custom_tags_text', agency_source)
        self.assertIn('Team access', agency_source)
        self.assertIn('/internal/operations/overview', internal_source)
        self.assertIn('/internal/release-readiness', internal_source)
        self.assertIn('/internal/review-queue/tenancies', internal_source)
        self.assertIn('/internal/review-queue/evidence', internal_source)
        self.assertIn('/internal/review-queue/history-imports', internal_source)
        self.assertIn('/internal/scoring/requests?limit=10', internal_source)
        self.assertIn('/internal/scoring/batches?limit=10', internal_source)
        self.assertIn('/internal/scoring/recalculate', internal_source)
        self.assertIn('/internal/automation/tasks/follow-ups', internal_source)
        self.assertIn('/organizations/directory/agencies', internal_source)
        self.assertIn('/internal/automation/tasks?due_only=true', internal_source)
        self.assertIn('/internal/notifications?limit=10', internal_source)
        self.assertIn('/internal/workers/runs?limit=10', internal_source)
        self.assertIn('/internal/audit-logs?limit=20', internal_source)
        self.assertIn('/internal/users?limit=25', internal_source)
        self.assertIn('/workspace-roles', internal_source)
        self.assertIn('Account roles', internal_source)
        self.assertIn('action_type=', internal_source)
        self.assertIn('Claim due tasks', internal_source)
        self.assertIn('Score controls', internal_source)
        self.assertNotIn("WORKSPACE_ROLE_OPTIONS", auth_source)
        self.assertNotIn("Open workspace as", auth_source)
        self.assertIn("switch assigned roles from the sidebar", auth_source)
        self.assertIn('/listings/open', marketplace_source)
        self.assertIn('/applications/mine', marketplace_source)
        self.assertIn('/listings/" + listing.id + "/applications', marketplace_source)
        self.assertIn('/tenancies/mine', records_source)
        self.assertIn('apiRequest("/properties/mine")', records_source)
        self.assertIn('apiRequest("/organizations/directory/agencies")', records_source)
        self.assertIn('apiRequest("/tenancies"', records_source)
        self.assertIn('counterparty_email', records_source)
        self.assertIn("Save property setup", records_source)
        self.assertIn('/request-review', records_source)
        self.assertIn('/confirm', records_source)
        self.assertIn('/evidence', records_source)
        self.assertIn('/evidence/tenancies/" + tenancyId + "/artifacts', records_source)
        self.assertIn('/evidence/" + evidence.id + "/artifact-access', records_source)
        self.assertIn('/history-imports/mine', records_source)
        self.assertIn('/history-imports/" + historyImport.id + "/submit', records_source)
        self.assertIn('/reference-requests/mine', records_source)
        self.assertIn('/reference-requests/tenancies/" + tenancy.id', records_source)
        self.assertIn('/evidence/tenancies/" + referenceRequest.tenancy_id + "/artifacts', records_source)
        self.assertIn('/reference-requests/" + referenceRequest.id + "/fulfill', records_source)
        self.assertIn('/payments/tenancies/" + tenancy.id', operations_source)
        self.assertIn('/payments/" + payment.id + "/proof', operations_source)
        self.assertIn('/payments/" + payment.id + "/decision', operations_source)
        self.assertIn('/deposits/tenancies/" + tenancy.id', operations_source)
        self.assertIn('/deposits/" + depositRecord.id + "/settlement', operations_source)
        self.assertIn('/deposits/" + depositRecord.id + "/dispute', operations_source)
        self.assertIn('/maintenance-tickets/tenancies/" + tenancy.id', operations_source)
        self.assertIn('/maintenance-tickets/" + ticket.id + "/acknowledge', operations_source)
        self.assertIn('/maintenance-tickets/" + ticket.id + "/resolve', operations_source)
        self.assertIn('/maintenance-tickets/" + ticket.id + "/dispute', operations_source)
        self.assertIn('Dispute desk', operations_source)
        self.assertIn('/trust-scores/mine', trust_source)
        self.assertIn('import { useSession } from "../app/session.js"', trust_source)
        self.assertIn('var session = useSession();', trust_source)
        self.assertIn('/trust-scores/mine/history', trust_source)
        self.assertIn('/trust-events/mine', trust_source)
        self.assertIn('/organizations/directory/agencies', trust_source)
        self.assertIn('/consents/trust-report', trust_source)
        self.assertIn('/consents/trust-report/access-history', trust_source)
        self.assertIn("ScoreContributionPanel", trust_source)
        self.assertIn("ScoreContributionPanel", agency_source)
        self.assertIn("ScoreFormulaReference", internal_source)
        self.assertIn("buildScoreContributionRows", score_transparency_source)
        self.assertIn("buildVerificationContributionRows", score_transparency_source)
        self.assertIn("score_inputs", score_transparency_source)
        self.assertIn("ScoreContributionPanel", score_component_source)
        self.assertIn("Scoring formula reference", score_component_source)

    def test_frontend_docs_track_localization_before_visual_redesign(self) -> None:
        readme_source = (ROOT / "README.md").read_text(encoding="utf-8")
        roadmap_source = (ROOT / "docs" / "ROADMAP.md").read_text(encoding="utf-8")
        sprint_source = (ROOT / "docs" / "SPRINTS.md").read_text(encoding="utf-8")

        self.assertIn("Sprint 18: Bilingual Frontend Localization", roadmap_source)
        self.assertIn("Sprint 18: Bilingual Frontend Localization", sprint_source)
        self.assertIn("Sprint 19: Compact Workspace And Cinematic Visual System", sprint_source)
        self.assertIn("bilingual frontend localization", readme_source.lower())
        self.assertIn("bootstrap_workstation.ps1", readme_source)
        self.assertIn("AGENTS.md", readme_source)
        self.assertIn("docs/HANDOFF.md", readme_source)
        self.assertIn("docs/WORKFLOW_GAPS.md", readme_source)
        self.assertIn("docs/WORKFLOW_QA_PLAN.md", readme_source)
        self.assertIn("docs/MANUAL_QA_RUNBOOK.md", readme_source)
        self.assertIn("docs/MANUAL_QA_CHECKLIST.md", readme_source)
        self.assertIn("docs/MANUAL_QA_RESULTS.md", readme_source)
        self.assertIn("docs/WORKSTATION_SYNC.md", readme_source)
        self.assertIn("docs/GITHUB_BOOTSTRAP.md", readme_source)
        self.assertIn("docs/CODEBASE_REFERENCE.md", readme_source)
        self.assertIn("docs/WORKFLOW_MAP.md", readme_source)
        self.assertIn("docs/WORKFLOW_DIAGRAMS.md", readme_source)
        self.assertIn("workflow QA master plan", sprint_source)
        self.assertIn("explicit account workspace-role entitlements", readme_source)
        self.assertIn("explicit account workspace-role entitlements", roadmap_source)
        self.assertIn("explicit account workspace-role entitlements", sprint_source)


if __name__ == "__main__":
    unittest.main()
