"""Add string enums and fix fks

Revision ID: c2f738bf0534
Revises: b42be0da05a0
Create Date: 2026-03-08 12:18:26.959344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2f738bf0534'
down_revision: Union[str, Sequence[str], None] = 'b42be0da05a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('OPEN', 'RESOLVED', 'APPROVED', name='ticketstatus'),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('tickets_tenant_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['creator_id'], ['id'])
    op.drop_column('tickets', 'tenant_id')
    op.drop_column('tickets', 'resolved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_tenant_id_fkey'), 'tickets', 'users', ['tenant_id'], ['id'])
    op.alter_column('tickets', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OPEN', 'RESOLVED', 'APPROVED', name='ticketstatus'),
               nullable=False)
    op.drop_column('tickets', 'creator_id')
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
